/*
 * PUEDE INCLUIR EN ESTE FICHERO LAS DEFICIONES QUE NECESITAN COMPARTIR
 * EL MÁSTER, LOS SERVIDORES Y LA BIBLIOTECA DE CLIENTE, SI ES QUE LAS HUBIERA.
 */

#ifndef _COMMON_H
#define _COMMON_H        1

#endif // _COMMON_H
