/*
 * PUEDE INCLUIR DEFINICIONES COMPARTIDAS ENTRE EL MASTER Y LOS PROCESOS QUE
 * ACTUÁN DE CLIENTES DEL MISMO (LA BIBLIOTECA DE CLIENTE Y LOS SERVIDORES),
 * SI LAS HUBIERA.
 */

#ifndef _MASTER_H
#define _MASTER_H        1


#endif // _MASTER_H

