/*
 * PUEDE INCLUIR DEFINICIONES COMPARTIDAS ENTRE EL SERVER Y LOS PROCESOS QUE
 * ACTUÁN DE CLIENTES DEL MISMO (LA BIBLIOTECA DE CLIENTE),
 * SI LAS HUBIERA.
 */

#ifndef _SERVER_H
#define _SERVER_H        1

#endif // _SERVER_H

